language: node_js
node_js:
  - "8"
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"

env:
  - BROWSER=true
  - NODE=true

install:
  - npm install

script:
  - ./run-tests.sh